name: college
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
# Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  connectivity_plus : ^5.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1   

  #firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/user/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
  
  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700
       - asset: assets/fonts/Poppins-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/Poppins-Italic.ttf
         style: italic
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
