// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOThShuoVGvYWpOKboP_5tmzv8_ZExJxY',
    appId: '1:420453752943:web:39b2b26eb6be870d182d9a',
    messagingSenderId: '420453752943',
    projectId: 'campus-care-4e923',
    authDomain: 'campus-care-4e923.firebaseapp.com',
    storageBucket: 'campus-care-4e923.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabJkCQrEN6T-bYims9oDAFbTe8E_47UY',
    appId: '1:420453752943:android:e1ef1d92d96878fe182d9a',
    messagingSenderId: '420453752943',
    projectId: 'campus-care-4e923',
    storageBucket: 'campus-care-4e923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5NwBuX23CBe6LfF6W3Q057VTYctvMdhs',
    appId: '1:420453752943:ios:4f72b8fe590859c2182d9a',
    messagingSenderId: '420453752943',
    projectId: 'campus-care-4e923',
    storageBucket: 'campus-care-4e923.appspot.com',
    androidClientId: '420453752943-bu48m1p1i25bp7oijpqhh4m71rgjhfed.apps.googleusercontent.com',
    iosClientId: '420453752943-oge1ir5fsvva17kusaj1ej3grsvif92s.apps.googleusercontent.com',
    iosBundleId: 'com.example.college',
  );
}
